[package]
name = "imagelib"
version = "0.1.0"
edition = "2024"

[dependencies]
load_image = "3.3.1"
minifb = "0.28.0"
serde = { version = "1.0.228", features = ["alloc", "derive", "rc", "serde_derive"] }


[profile.release]
debug = true

